/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package btree.java;

public class Btree {
    
    public static class Node {
        Object val;
        Node left;
        Node right;

        public Node(Integer value) {
            this.val = value;
        }

        public Node(String value) {
            this.val = value;
        }

        public Node(Float value) {
            this.val = value;
        }

        @Override
        public String toString() {
            String nodeString = "Node()";
            
            if (this.val instanceof Integer) {
                nodeString = String.format("Node(%d)", this.val);
            } else if (this.val instanceof String) {
                nodeString = String.format("Node(%s)", this.val);
            } else if (this.val instanceof Float) {
                nodeString = String.format("Node(%.2f)", this.val);
            }

            return nodeString;
        }
    }

    public Btree() {}

    public static void main(String... args) {
        final String message = "\n"
            + "Btree-java is a port of the (Python) Binarytree library.\n"
            + "It has most of Binarytree's functionality, but lacks support for Graphviz and Jupyter Notebooks.\n"
            + "Btree-java includes matching unit tests.\n";
        
        System.out.println(message);
    }
}


