/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package btree.java;

public class Btree {
    Object nodeValue;
    public boolean someLibraryMethod() {
        return true;
    }

    public void Btree(Integer value) {
        this.nodeValue = value;
    }

    public void Btree(String value) {
        this.nodeValue = value;
    }

    public void Btree(Float value) {
        this.nodeValue = value;
    }

    public static void main(String[] args) {
        final String message = "\n"
            + "Btree-java is a port of the (Python) Binarytree library.\n"
            + "It has most of Binarytree's functionality, but lacks support for Graphviz and Jupyter Notebooks.\n"
            + "Btree-java includes matching unit tests.\n";
        
        System.out.println(message);
    }
}


