/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package btree.java;

import org.junit.Test;
import static java.util.Collections.singletonList;
import static org.junit.Assert.*;

public class BtreeTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Btree classUnderTest = new Btree();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test 
    public void main() {
        Btree.main(new String[] {});
    }
}
