/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package btree.java;

import org.junit.Test;
import static org.junit.Assert.*;

public class BtreeTest {
    @Test public void testConstructor() {
        Integer num = Integer.valueOf(76);
        Btree btree = new Btree(num);
        assertEquals(num, btree.nodeValue);
        String str = String.valueOf("ABC");
        Btree btree2 = new Btree(str);
        assertEquals(str, btree2.nodeValue);
        Float flt = Float.valueOf(25.53f);
        Btree btree3 = new Btree(flt);
        assertEquals(flt, btree3.nodeValue);
    }

    @Test public void testtoString() {
        Integer num = Integer.valueOf(76);
        Btree btree = new Btree(num);
        String btreeAsString = "Node(76)";
        assertEquals(btreeAsString, btree.toString());
        String str = String.valueOf("ABC");
        Btree btree2 = new Btree(str);
        String btree2AsString = "Node(ABC)";
        assertEquals(btree2AsString, btree2.toString());
        Float flt = Float.valueOf(25.53f);
        Btree btree3 = new Btree(flt);
        String btree3AsString = "Node(25.53)";
        assertEquals(btree3AsString, btree3.toString());
    }

    @Test 
    public void main() {
        Btree.main(new String[] {});
    }
}
