/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package btree.java;

import static org.junit.jupiter.api.Assertions.assertEquals;


public class BtreeTest {
    
    public void testNodeToString() {
        assertEquals("Node(1)", new Btree.Node<>(1).toString());
        assertEquals("Node(1.50)", new Btree.Node<>(1.50f).toString());
        assertEquals("Node(A)", new Btree.Node<>("A").toString());
    }

    public void main() {
        Btree.main(new String[] {});
    }
}
